export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const DO_LOGOUT = 'DO_LOGOUT';

export const REQUEST_AUTHENTICATE = 'REQUEST_AUTHENTICATE';
export const DO_AUTHENTICATE = 'DO_AUTHENTICATE';
export const AUTH_SUCCESSED = 'AUTH_SUCCESSED';
export const AUTH_FAILED = 'AUTH_FAILED';