export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const DO_GET_ALL_POSTS = 'DO_GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESSED = 'GET_ALL_POSTS_SUCCESSED';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

export const GET_ALL_POSTS_NOT_SENTIMENT = 'GET_ALL_POSTS_NOT_SENTIMENT';
export const DO_GET_ALL_POSTS_NOT_SENTIMENT = 'DO_GET_ALL_POSTS_NOT_SENTIMENT';
export const GET_ALL_POSTS_NOT_SENTIMENT_SUCCESSED = 'GET_ALL_POSTS_NOT_SENTIMENT_SUCCESSED';
export const GET_ALL_POSTS_NOT_SENTIMENT_FAILED = 'GET_ALL_POSTS_NOT_SENTIMENT_FAILED';

export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';
export const GET_ALL_CONTENT_SUCCESSED = 'GET_ALL_CONTENT_SUCCESSED';
export const GET_ALL_CONTENT_FAILED = 'GET_ALL_CONTENT_FAILED';

export const GET_ALL_CONTENT_ASSIGNED = 'GET_ALL_CONTENT_ASSIGNED';
export const GET_ALL_CONTENT_ASSIGNED_SUCCESSED = 'GET_ALL_CONTENT_ASSIGNED_SUCCESSED';
export const GET_ALL_CONTENT_ASSIGNED_FAILED = 'GET_ALL_CONTENT_ASSIGNED_FAILED';

export const GET_TOTAL_CONTENT_REQUEST = 'GET_TOTAL_CONTENT_REQUEST';
export const GET_TOTAL_CONTENT_SUCCESS = 'GET_TOTAL_CONTENT_SUCCESS';
export const GET_TOTAL_CONTENT_FAILURE = 'GET_TOTAL_CONTENT_FAILURE';