export const DO_CHECK_SENTIMENT = 'DO_CHECK_SENTIMENT';
export const CHECK_SENTIMENT_SUCCESSED = 'CHECK_SENTIMENT_SUCCESSED';
export const CHECK_SENTIMENT_FAILED = 'CHECK_SENTIMENT_FAILED';
export default {
  UPDATE_POST_SENTIMENT: 'UPDATE_POST_SENTIMENT',
  UPDATE_COMMENT_SENTIMENT: 'UPDATE_POST_SENTIMENT',
  REQUEST_SENTIMENT_REPORT: 'REQUEST_SENTIMENT_REPORT',
  REQUEST_SENTIMENT_REPORT_PENDING: 'REQUEST_SENTIMENT_REPORT_PENDING',
  REQUEST_SENTIMENT_REPORT_SUCCESS: 'REQUEST_SENTIMENT_REPORT_SUCCESS',
  REQUEST_SENTIMENT_REPORT_FAILURE: 'REQUEST_SENTIMENT_REPORT_FAILURE',
};
